# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fa4d269d-2623-4770-a050-f34b00ad2abb";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/64ac12ba-2da8-45ba-9d19-95e3fc587f14";
    fsType = "ext2";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f032a882-83cb-49c6-bb99-6680122326e9";
    fsType = "xfs";
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/87dd8fd1-5bc5-42cf-985e-e891a4ecc4cb";
    fsType = "xfs";
  };

  swapDevices = [ ];

}
